#! /data/data/com.termux/files/usr/bin/bash
	R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'
	echo
	echo $(clear)
	echo
echo -e "$G"
echo "            _    ____  _  _______ ___   ___  _"
echo "           / \  |  _ \| |/ /_   _/ _ \ / _ \| |"
echo "          / _ \ | |_) | ' /  | || | | | | | | |"
echo "         / ___ \|  __/| . \  | || |_| | |_| | |___"
echo "        /_/   \_\_|   |_|\_\ |_| \___/ \___/|_____|"
echo -e "$R           Cesar Hacker The Gray"
echo
echo
sleep 6
echo 
echo $(clear)
echo
echo -e "$C Brindando modos"
echo
sleep 7

chmod 777 $HOME/apktool/apktool
chmod 777 $HOME/apktool/apktool-2.2.0.jar
chmod 777 $HOME/apktool/LICENSE
chmod 777 $HOME/apktool/README.md
chmod 777 $HOME/apktool/openjdk/bin/java
chmod 777 $HOME/apktool/.devil
chmod 777 $HOME/apktool/libld.so





echo $(clear)
echo -e "$C Instalando requisitos"
sleep 4

mkdir -p $HOME/apktool/.lib

mv $HOME/apktool/.devil $HOME/apktool/.lib
mv $HOME/apktool/libld.so $HOME/apktool/.lib




echo $(clear)

echo -e "$C Moviendo apktool a sistema"

rm -rf $PREFIX/bin/apktool
rm -rf $PREFIX/bin/java

cp $HOME/apktool/apktool $PREFIX/bin
cp $HOME/apktool/openjdk/bin/java $PREFIX/bin
echo
echo
echo -e "$C puedes usar apktool satisfactoriamente att.. $Y César"
echo
echo
